/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg1.edd;

import java.io.BufferedWriter; 
import java.io.FileWriter; 
import java.io.IOException;   
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import proyecto.pkg1.edd.Grafo;

/**
 *
 * @author a-utr
 */
public class Interfaz2 extends javax.swing.JFrame {
    private Interfaz ventanaAnterior;
    private Grafo miGrafo;
    
    private ArrayList<String> listaUsuarios;
    private ArrayList<String> listaRelaciones;
    private String rutaDelArchivo;

    /**
     * Creates new form Interfaz2
     */

    public Interfaz2() {
        initComponents();
        this.miGrafo = new Grafo (true,100);
    }
    
    
    public Interfaz2(Interfaz ventanaAnterior, Grafo grafoConstruido, ArrayList<String> usuarios, ArrayList<String> relaciones, String ruta) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        this.miGrafo = grafoConstruido;

        this.listaUsuarios = usuarios;
        this.listaRelaciones = relaciones;
        this.rutaDelArchivo = ruta;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(214, 231, 248));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 150, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jButton2.setText("➖ Eliminar Usuario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 150, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jButton3.setText("Crear Relacion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 120, -1));

        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton4.setText("Mostrar Grafo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 140, -1));

        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton5.setText("Volver");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 160, -1));
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 160, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Ingrese el segundo usuario:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Crear Relaciones:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 102));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 460, 10));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Ingrese el primer usuario:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 480, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
/**
     * Gestiona el evento de clic del botón "Volver"
     * @param evt Objeto que encapsula la información del evento.
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    if (this.ventanaAnterior != null) {
        this.ventanaAnterior.actualizarTextAreaVisual(); 
        this.ventanaAnterior.setVisible(true);
    }
    this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed
/**
     * Maneja el botón "Mostrar Grafo"
     * Verifica que la instancia 'miGrafo' no sea nula
     * Si el grafo existe, llama al método {@code miGrafo.mostrarGrafo()} para abrir la ventana de visualización
     * @param evt El evento de clic que disparó esta acción.
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (miGrafo != null) {
            miGrafo.mostrarGrafo();
        } else {
            JOptionPane.showMessageDialog(this, "Error: El grafo no ha sido cargado.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed
/**
     * Maneja el botón "Eliminar Usuario" 
     * Obtiene el usuario
     * Elimina el vértice de 'miGrafo'.
     * Elimina el usuario de 'listaUsuarios'.
     * Elimina todas las relaciones que incluyan a ese usuario de 'listaRelaciones'.
     * Llama a 'reescribirArchivoTXT()' para guardar los cambios en el archivo.
     * @param evt Evento de clic que disparó esta acción.
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String usuarioAEliminar = jTextField1.getText().trim();
        if (!usuarioAEliminar.startsWith("@")) {
            usuarioAEliminar = "@" + usuarioAEliminar;
        }

        if (!this.listaUsuarios.contains(usuarioAEliminar)) {
            JOptionPane.showMessageDialog(this, "El usuario '" + usuarioAEliminar + "' no existe.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String finalUsuarioAEliminar = usuarioAEliminar; 

        this.miGrafo.eliminarVertice(usuarioAEliminar);
        this.listaUsuarios.remove(usuarioAEliminar);
        this.listaRelaciones.removeIf(rel -> rel.contains(finalUsuarioAEliminar));


        if (reescribirArchivoTXT()) {
            JOptionPane.showMessageDialog(this, "Usuario eliminado exitosamente.");
            jTextField1.setText("");

        }
      
    }//GEN-LAST:event_jButton2ActionPerformed
/**
     * Maneja el botón "Crear Relación" 
     * Obtiene los usuarios
     * Verifica que la relación no exista ya 
     * Inserta la arista en 'miGrafo' y agrega la 
     * relación a 'listaRelaciones'.
     * Guardar los cambios en el archivo
     * @param evt Evento de clic que disparó esta acción
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String u1 = jTextField2.getText().trim();
        String u2 = jTextField4.getText().trim();

        if (!u1.startsWith("@")) u1 = "@" + u1;
        if (!u2.startsWith("@")) u2 = "@" + u2;

        if (u1.isEmpty() || u2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar ambos usuarios.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!this.listaUsuarios.contains(u1) || !this.listaUsuarios.contains(u2)) {
            JOptionPane.showMessageDialog(this, "Uno o ambos usuarios no existen.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nuevaRelacion = u1 + ", " + u2;
        String relacionInversa = u2 + ", " + u1;

        if (this.listaRelaciones.contains(nuevaRelacion) || this.listaRelaciones.contains(relacionInversa)) {
            JOptionPane.showMessageDialog(this, "Esa relación ya existe.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        this.miGrafo.insertarArista(u1, u2);
        this.listaRelaciones.add(nuevaRelacion);

        if (reescribirArchivoTXT()) {
            JOptionPane.showMessageDialog(this, "Relación creada exitosamente.");
            jTextField2.setText("");
            jTextField4.setText("");

        }
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

       miGrafo.mostrarGrafo();

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * Re-escribe el archivo .txt completo usando las listas en memoria.
     * @return true si fue exitoso, false si hubo un error.
     */
    private boolean reescribirArchivoTXT() {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(this.rutaDelArchivo))) {
            
            writer.write("usuarios");
            writer.newLine();
            for (String usuario : this.listaUsuarios) {
                writer.write(usuario);
                writer.newLine();
            }

            writer.newLine();
            writer.write("relaciones");
            writer.newLine();
            for (String relacion : this.listaRelaciones) {
                writer.write(relacion);
                writer.newLine();
            }
            
            System.out.println("Archivo .txt actualizado exitosamente.");
            return true;

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error fatal al re-escribir el archivo: " + e.getMessage(), "Error de Archivo", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
